# Gauss Elimination

In [1]:
import numpy as np
c = np.array([[25,5,1,106.8],[64,8,1,177.2],[144,12,1,279.2]])
x = np.ones(3)
n = len(c)
print(c)
for i in range(0,n):
    for j in range((i+1),n):
        c[j] = c[j]-(c[i]*(c[j][i])/(c[i][i]))
        

for i in range(n-1,-1,-1):
    y = 0
    for j in range(n-1,-1,-1):
        if i != j:
            if i < j:
                y = y + ((c[i][j]) * x[j])
            else:
                y = y + c[i][j]
    y = c[i][3] - y
    x[i] = y / c[i][i]

    
for i in range(0,int(len(x))):
    print(f"x{i+1} is :", round(x[i],5))

[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]
x1 is : 0.29048
x2 is : 19.69048
x3 is : 1.08571


# Jacobi

In [4]:
import numpy as np
import pandas as pd

df = pd.DataFrame(columns=['x1','x2','x3'])
c = np.array([[8,-3,2,45],[4,11,-1,71],[6,3,12,35]])
x = np.ones(3)

x = np.zeros(len(c))
xcop = np.zeros(len(c))
for k in range(0,15):
    for i in range(0,len(c)):
        y = 0
        for j in range(0,len(c)):
            if i != j:
                y = y + (c[i][j] * x[j])
        y = c[i][len(c)] - y
        xcop[i] = y / c[i][i]
    for i in range(0,len(x)):
        x[i] = xcop[i]
    df.loc[k+1] = [x[0],x[1],x[2]]
        
round(df,4)

x1      x2      x3
1   5.6250  6.4545  2.9167
2   7.3163  4.6742 -1.5095
3   7.7552  3.6569 -1.9100
4   7.4738  3.4608 -1.8752
5   7.3916  3.5663 -1.6855
6   7.3837  3.6135 -1.6707
7   7.3977  3.6177 -1.6786
8   7.4013  3.6119 -1.6866
9   7.4011  3.6098 -1.6869
10  7.4004  3.6099 -1.6863
11  7.4003  3.6102 -1.6860
12  7.4003  3.6103 -1.6860
13  7.4004  3.6102 -1.6861
14  7.4004  3.6102 -1.6861
15  7.4004  3.6102 -1.6861

# Jorden

In [3]:

c = np.array([[25,5,1,106.8],[64,8,1,177.2],[144,12,1,279.2]])
x = np.ones(3)
n = len(c)

for i in range(0,n):
    c[i] = c[i] / c[i][i]
    for j in range(0,n):
        if i != j:
            c[j] = c[j] - c[j][i] * c[i]
            
for i in range(0,n):
    print(f"x{i+1} is :",c[i][3])

x1 is : 0.2904761904761916
x2 is : 19.690476190476172
x3 is : 1.0857142857143551


# Seidel

In [11]:

A = [[8,-3,2],[4,11,-1],[6,3,12]]

B = [45,71,35]



X = [0, 0, 0]
S = [0, 0, 0]
k = 0

while k != 6:
    S[0] = (B[0] - (A[0][1] * X[1]) - (A[0][2] * X[2])) / A[0][0]
    S[1] = (B[1] - (A[1][0] * X[0]) - (A[1][2] * X[2])) / A[1][1]
    S[2] = (B[2] - (A[2][0] * X[0]) - (A[2][1] * X[1])) / A[2][2]
    X[0] = S[0]
    X[1] = S[1]
    X[2] = S[2]
    k = k + 1
    
    
print('''Resut:x= {0:.3f}, y={1:.3f}, z={2:.3f} Number Of Iterations: {3}'''.format(float(S[0]), float(S[1]), float(S[2]), k))

Resut:x= 7.384, y=3.613, z=-1.671 Number Of Iterations: 6
